---
title: "Aula7_NLP"
author: "Ricardo Primi"
date: "11/8/2020"
output: html_document
---
## Problema

## Trabalhando com textos usando o `tidytext`

* https://www.tidytextmining.com/index.html


### Bibliotecas
```{r}

 library(readxl)
 library(tidyverse)


```

### Dados
```{r}
 
 frameworks <- read_excel("../dados/sems_definitions.xlsx") 

```

### Explorando dados
```{r}

library(sjmisc)

frq(frameworks$system)
frq(frameworks$domain)
frq(frameworks$facet)


```

### Preparação dos dados para tokenização

```{r}

library(stringr)

  frameworks <- frameworks %>%
    mutate(
      domain = str_to_lower(domain),
      facet  = str_to_lower(facet),
      definition = str_to_lower(definition)
  )

  frameworks$definition[1:3] %>% paste(collapse =  " ")
  
  frameworks2 <- frameworks %>% 
    group_by(system, facet) %>%
    summarise(
      domain = first(domain),
      definition = paste(definition, collapse = " ")
    ) 
 
```


  
### Tokenize
```{r}

 library(tidytext)
# Tokenize palvras 
  frameworks3 <- frameworks2 %>% 
    ungroup  %>%
    unnest_tokens(words, definition)

  
 length(unique(frameworks3$words))


```
### Explorando as palavras
```{r}

frameworks3  %>% count(words, sort = TRUE)

```

### Stop words and frequência de palavras

Snowball: http://snowball.tartarus.org/algorithms/english/stop.txt
NLTK: http://www.nltk.org/
Stopwords ISO: https://github.com/stopwords-iso



```{r}

  words <-  unique(
    c(stopwords::data_stopwords_snowball$en,
      stopwords::data_stopwords_nltk$en,
      stopwords::data_stopwords_stopwordsiso$en
      )
  )

  stopwords  <-tibble(
    words = words
  )

  
# Palavras gerais   
    frameworks3 %>%
        count(words, sort = TRUE) %>%
        filter(n > 50 ) %>%
        mutate(words = reorder(words, n)) %>%
       ggplot(aes(words, n)) +
        geom_col() +
        xlab(NULL) +
        coord_flip()
 
       
# Remove stopwords
     frameworks3 %>%
        count(words, sort = TRUE) %>%
        anti_join(stopwords) %>%
        filter(n > 15)  %>%
        mutate(word = reorder(words, n)) %>%
        ggplot(aes(word, n)) +
        geom_col() +
        xlab(NULL) +
        coord_flip()

# Word cloud   
   library(wordcloud)

   frameworks3 %>%
        anti_join(stopwords) %>%
        count(words) %>%
        with(wordcloud(words, n, 
          colors = brewer.pal(12, "Set1"),
            max.words = 100)) 

    stopwords[221, "words"] <- "pra"
    stopwords[222, "words"] <- "dá"


```

### Análise de similaridade usando o word embeddings 

* Faca o download do arquivo: 
http://nlp.stanford.edu/data/glove.6B.zip

De Stanford https://nlp.stanford.edu/projects/glove/


```{r}

  library(readr)

 # Lê word embeddings
  glove_wv_300 <- read_delim(
    file = "../../glove.6B.300d.txt", 
    delim = " ",quote="", 
    skip = 1,  
    col_names = FALSE, 
    progress = TRUE)
  
  names(glove_wv_300)[1]<-"words"
  names(glove_wv_300)[2:301]<-paste("d", 1:300, sep= "")
  
  glove_wv_300[2000:4000, ] %>% view

```

```{r}

 frameworks4 <- frameworks3 %>% 
  left_join( glove_wv_300, by = "words") %>%
  filter(!is.na(d1))

 save(frameworks4, file = "frameworks4.RData")

```

### Visualizando clusters usando tsn-e 
* https://lvdmaaten.github.io/tsne/
* https://distill.pub/2016/misread-tsne/

```{r}

  library(Rtsne)

  frameworks5 <- frameworks4 %>% 
    group_by(system, facet) %>%
    summarise(
      across(d1:d300, mean, na.rm=TRUE)
     )
  
  tsne <- frameworks5 %>% 
  select(3:302) %>%
  Rtsne( perplexity = 18) 
  
  frameworks5 <- frameworks5 %>% bind_cols(as.data.frame(tsne$Y))
  
  
  names(frameworks5)
  
   library(ggrepel)
  library(ggthemes)
  library(RColorBrewer)
  
  ggplot(data = frameworks5,  
            mapping = aes(
             y = V1,
             x = V2,
            color = system) 
           ) +
          
         geom_point()  +
                  
         geom_text_repel(
            aes(label=facet), 
            size=2, vjust=-1.2
            ) +
       theme_minimal() +
      scale_color_brewer() +
       theme(legend.position = "none") 
  
   frameworks5 %>%
    filter( system == "MACM") %>%
    ggplot( mapping = aes(
             y = V1,
             x = V2) 
           ) +
          
         geom_point()  +
                  
         geom_text_repel(
            aes(label=facet), 
            size=2, vjust=-1.2
            ) +
       theme_minimal() +
      scale_color_brewer() +
       theme(legend.position = "none") 
  
  
   frameworks5 %>%
    filter( system == "OECD") %>%
    ggplot( mapping = aes(
             y = V1,
             x = V2) 
           ) +
          
         geom_point()  +
                  
         geom_text_repel(
            aes(label=facet), 
            size=2, vjust=-1.2
            ) +
       theme_minimal() +
      scale_color_brewer() +
       theme(legend.position = "none") 

   
   

```

